export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  LEAVE_ADMIN = "LEAVE_ADMIN",
  WORK_CERTIFICATION_ADMIN = "WORK_CERTIFICATION_ADMIN",
  CLASS_ATTENDANCE_ADMIN = "CLASS_ATTENDANCE_ADMIN",
  TEACHER = "TEACHER",
  GENERAL_STAFF = "GENERAL_STAFF",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
}
